sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: 152.136.52.162
    port: 3306
    database: sky_take_out
    username: root
    password: mysql2023.1
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tBM5YX7BffMuepviSzN
    access-key-secret: 4DoZUeQfT5f0iNBBoWUQoaBotATBfI
    bucket-name: sky-202310
